/**
 * Engine internal constants.
 * Core engine parameters for world creation, zones, obstacles, and risk calculations.
 */

export const ENGINE_CONSTANTS = {
  MS_PER_SECOND: 1000,
  TRAIL_BUFFER_SIZE: 13,
  FOOD_BUFFER_SIZE: 5,
  MAX_DEPTH: 3,
  MAX_CELL_SIZE: 80,
  DEFAULT_CAMERA_FOV: 60,
  DEFAULT_ZOOM: 1,
  TICK_RATE: 60,
  HIT_RADIUS_MULT_ORG: 2.5,
  HIT_RADIUS_MULT_ORG_FALLBACK: 2,
  HIT_RADIUS_MULT_FOOD: 2,
  GRID_FALLBACK_MULT: 2,
  WORLD_AGE_FALLBACK_TPS: 60,
  BUFFER_GROWTH_FACTOR: 1.5,
  BUFFER_SHRINK_FACTOR: 1.25,
  BUFFER_MIN_CAPACITY: 100,
  EXTINCTION_THRESHOLD_LOW: 5,
  EXTINCTION_RISK_HIGH: 0.9,
  EXTINCTION_RISK_MEDIUM: 0.5,
  RISK_COLOR_THRESHOLD: 0.8,
  RISK_FACTOR_OFFSET: 0.1,

  // Ecological zones - radius multipliers
  ZONE_OASIS_RADIUS_MULT: 0.15,
  ZONE_DESERT_RADIUS_MULT: 0.2,
  ZONE_HUNTING_RADIUS_MULT: 0.12,
  ZONE_SANCTUARY_RADIUS_MULT: 0.1,

  // Ecological zones - position multipliers
  ZONE_HUNTING_X_MULT: 0.75,
  ZONE_HUNTING_Z_MULT: 0.25,
  ZONE_SANCTUARY_X_MULT: 0.25,
  ZONE_SANCTUARY_Z_MULT: 0.75,
  ZONE_CENTER_MULT: 0.5,

  // Obstacle configuration
  OBSTACLE_COUNT: 12,
  OBSTACLE_MIN_RADIUS: 12,
  OBSTACLE_RADIUS_RANGE: 25,

  // Initial statistics values
  INITIAL_GENERATION: 0,
  INITIAL_MAX_GENERATION: 1,
  INITIAL_STAT_VALUE: 0,

  // RNG and time parameters
  SEED_LIMIT: 0xffffffff,

  // Risk and population parameters
  IDEAL_PREDATOR_RATIO: 0.1,
  RISK_SCALING_FACTOR: 0.5,
  EXTINCTION_RISK_ZERO: 0,
  EXTINCTION_RISK_DEAD: 1,
  EXTINCTION_RISK_NO_PREY: 0.8,
  EXTINCTION_RISK_NO_PREDATOR: 0.1,
  VOLUME_EXPONENT: 3,
  FULL_PERCENT: 100,
} as const;
